<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ng nhp</name>
   <tag></tag>
   <elementGuidId>866937cb-1b79-40c6-a3cc-d4a87430aa8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.form-control.btn-submit.text-center.style2-input.text-white.fw-600.olm-btn-primary.border-0.p-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmInputLogin']/div[4]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7e5763ca-074a-43d6-86e8-4959b9ce5f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control btn-submit text-center style2-input text-white fw-600 olm-btn-primary border-0 p-0 </value>
      <webElementGuid>738564ce-ac30-4c61-abe5-0fa33f234eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng nhập</value>
      <webElementGuid>c9d7b35b-c2af-4fed-a168-76b1892a9081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInputLogin&quot;)/div[@class=&quot;col-sm-12 p-0 text-left&quot;]/div[@class=&quot;form-group mb-1&quot;]/button[@class=&quot;form-control btn-submit text-center style2-input text-white fw-600 olm-btn-primary border-0 p-0&quot;]</value>
      <webElementGuid>1e302c0d-7824-42de-a066-f2960a789b47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmInputLogin']/div[4]/div/button</value>
      <webElementGuid>b0acf67d-b736-411c-9291-588c494b3795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quên mật khẩu'])[1]/following::button[1]</value>
      <webElementGuid>cf05097a-f59f-4fb2-b7eb-a8281be728ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ghi nhớ đăng nhập'])[1]/following::button[1]</value>
      <webElementGuid>d1a1c817-5138-49ec-b896-9c21da81baba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng ký'])[1]/preceding::button[1]</value>
      <webElementGuid>df96b703-1ad0-4d1f-a8db-3ba0951f3da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>427ccd71-3657-4802-b8f5-8cb887d9cb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Đăng nhập' or . = 'Đăng nhập')]</value>
      <webElementGuid>b0297def-b066-43bb-a58b-30992c98911f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
