<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Hu Giang</name>
   <tag></tag>
   <elementGuidId>8e0f5aa0-f349-479d-a1c1-c452f8b0c932</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-82ht-result-fvev-66</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-82ht-result-fvev-66']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0315b024-d25f-4ab0-9aa8-2efe29f589b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>dc19d55d-e907-4232-9b29-74ce01dd103e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-82ht-result-fvev-66</value>
      <webElementGuid>d3a58c70-8b2b-43a1-bab1-1b19391ab554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d4f76ec7-87a7-4dec-bb03-050d2ff61368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>901a89b1-17af-4dcb-916b-e705b59a75b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-82ht-result-fvev-66</value>
      <webElementGuid>f0ce7465-f79b-4380-b733-fe849ee7daa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hậu Giang</value>
      <webElementGuid>b5f7b640-bb18-4fc5-8202-0cdbdcf141ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-82ht-result-fvev-66&quot;)</value>
      <webElementGuid>109fe151-a0d5-4563-97be-fbb145afb841</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-82ht-result-fvev-66']</value>
      <webElementGuid>be8af816-a8e8-41a0-a1a8-fe1ac507e623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-82ht-results']/li[29]</value>
      <webElementGuid>b8cb40b6-5d5b-435a-b9f6-8ace24566ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hải Phòng'])[3]/following::li[1]</value>
      <webElementGuid>bfd0ac1e-db39-4c8c-aa3c-6ea91a4f39f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hải Dương'])[2]/following::li[2]</value>
      <webElementGuid>62388eaa-e133-4042-ab15-0ed0bcd3ab11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hòa Bình'])[2]/preceding::li[1]</value>
      <webElementGuid>e1953c08-ec1b-45ce-b4b0-919486edd1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hưng Yên'])[2]/preceding::li[2]</value>
      <webElementGuid>d9feea3d-f486-4dc3-a480-554db5fbeb06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[29]</value>
      <webElementGuid>731d6ec1-04d0-4e2e-88a5-3f513c3864ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-82ht-result-fvev-66' and (text() = 'Hậu Giang' or . = 'Hậu Giang')]</value>
      <webElementGuid>4d511623-8544-49e7-959e-88a7f23b29a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
