<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Hi Phng</name>
   <tag></tag>
   <elementGuidId>8a601679-a381-416f-beaa-4f88f9224db3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-82ht-result-g0mq-30</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-82ht-result-g0mq-30']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7905b904-19d4-4382-a30b-5543532d92dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>12eb6dad-52b5-4c4d-91c4-c29bd1efb0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-82ht-result-g0mq-30</value>
      <webElementGuid>92487e26-6229-465f-98b3-ad305900dd4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>103712b2-5740-4117-a890-e95744cff36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a421ba1a-b305-416f-9cb0-19ff78f6b61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-82ht-result-g0mq-30</value>
      <webElementGuid>0246093c-87b4-450c-a8e4-98841d5ce49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hải Phòng</value>
      <webElementGuid>cb9ca655-297d-4a75-9790-38954ee69287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-82ht-result-g0mq-30&quot;)</value>
      <webElementGuid>5538a9c2-ed47-4b3f-9e7a-80fa0a016b69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-82ht-result-g0mq-30']</value>
      <webElementGuid>02955222-4a4c-4682-bcc8-434b080a1953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-82ht-results']/li[28]</value>
      <webElementGuid>de82fc57-0ba7-4eff-9613-9463c45c2224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hải Dương'])[2]/following::li[1]</value>
      <webElementGuid>f32ad752-8a7f-42a8-a009-ab315d407916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hà Tĩnh'])[2]/following::li[2]</value>
      <webElementGuid>9d437e79-12e9-4be9-9a4b-83c6f5a1e08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hậu Giang'])[3]/preceding::li[1]</value>
      <webElementGuid>65b16eeb-a054-40fc-bf44-677e7898fc6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hòa Bình'])[2]/preceding::li[2]</value>
      <webElementGuid>dac6f7ab-913f-45ac-aeb1-5d585d829340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[28]</value>
      <webElementGuid>80677f49-f664-4cbd-8355-5592f81b0dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-82ht-result-g0mq-30' and (text() = 'Hải Phòng' or . = 'Hải Phòng')]</value>
      <webElementGuid>e2027f2b-4d7f-4482-9be5-f193d88d8d5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
