<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hu Giang</name>
   <tag></tag>
   <elementGuidId>b621ab1a-6a5d-489f-b14d-977431cfb06c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-82ht-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-82ht-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ae09af2d-95e0-4094-bdcf-f6d073bed0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>8edf761a-50a7-4075-a5c9-40cd658895df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-82ht-container</value>
      <webElementGuid>486d83d9-feac-4b56-a34a-da660a0d8c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>8431041e-19e5-41e8-9923-15c36c04cfd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5d15b31f-d6a0-4198-8473-9c8ebc48c6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Hậu Giang</value>
      <webElementGuid>7b5fec87-1792-4e8a-ac40-8566461c5de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hậu Giang</value>
      <webElementGuid>875bff30-4caf-4e4f-9144-51efa42d8ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-82ht-container&quot;)</value>
      <webElementGuid>aa696973-f135-4abe-8d09-4719810fe138</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-82ht-container']</value>
      <webElementGuid>3220fddb-0881-4ac3-a1b0-c3740c0e30b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='setting-account']/div/div/div/span/span/span/span</value>
      <webElementGuid>eda41c6e-1234-4c51-97fb-d778728292d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn tỉnh/thành phố'])[1]/following::span[4]</value>
      <webElementGuid>9873b0c6-0cb1-45e5-80b3-01ef0ef9c5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn quận/huyện'])[1]/preceding::span[3]</value>
      <webElementGuid>be4264d6-7003-45d3-b597-a315119aaf59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vui lòng chọn giá trị'])[1]/preceding::span[3]</value>
      <webElementGuid>2809c1ae-beff-4d4d-a624-d6c52c29a776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>765cd63e-4988-4826-a623-9728f53ef328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-82ht-container' and @title = 'Hậu Giang' and (text() = 'Hậu Giang' or . = 'Hậu Giang')]</value>
      <webElementGuid>b6672827-d95f-46ab-ad32-524e6dcd1f4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
