<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hi Phng</name>
   <tag></tag>
   <elementGuidId>0bea63a1-c4ea-410b-957f-bb2f034b638a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-82ht-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-82ht-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d046d173-34cd-494e-b29a-6297370d0723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>fce7254e-51bb-4892-96f3-1ea348816d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-82ht-container</value>
      <webElementGuid>b0febb99-ed99-4798-9637-e688318062e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>f966862e-7018-4dc0-b6f4-63e3b399e2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>430525d0-dd41-4d39-8069-959575bd54bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Hải Phòng</value>
      <webElementGuid>5ab32449-a6e0-4b81-9bc7-1c708bbd1a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hải Phòng</value>
      <webElementGuid>3ad460ec-4528-46bd-a29a-5c7b57fb3514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-82ht-container&quot;)</value>
      <webElementGuid>33b30cfa-c12a-44ee-8b65-d100ae2cdf70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-82ht-container']</value>
      <webElementGuid>63c93958-af13-40db-87ad-db148ae0a0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='setting-account']/div/div/div/span/span/span/span</value>
      <webElementGuid>468b0b7d-439a-4d14-b518-15505b713a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn tỉnh/thành phố'])[1]/following::span[4]</value>
      <webElementGuid>69242470-5547-4452-ad8e-0e4770a1f5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn quận/huyện'])[1]/preceding::span[3]</value>
      <webElementGuid>5d9cb325-1da9-48e5-8cfe-5ea75cc9309c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vui lòng chọn giá trị'])[1]/preceding::span[3]</value>
      <webElementGuid>0d7899ea-01eb-48d5-862d-08ddbed8e4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>c5f77c83-0a5d-4140-9ca8-0e4c0f9cce3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-82ht-container' and @title = 'Hải Phòng' and (text() = 'Hải Phòng' or . = 'Hải Phòng')]</value>
      <webElementGuid>97965788-07de-4da4-9946-2ee117ae2636</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
