<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Trng Tiu hc Thun Hng</name>
   <tag></tag>
   <elementGuidId>488f614e-615e-46e3-967c-8b8ac1ec3788</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[5]/div/div[2]/div/div/div[1]/div[3]/div/span/span[1]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-sd6j-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>41d4d911-5578-4c85-bfcc-c37709afd373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>59135c38-0870-40a3-a4ce-f9f44f4d378c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-sd6j-container</value>
      <webElementGuid>7ef4ce94-b06b-4f8e-b395-53f1adb16b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>01c14789-d1a3-4572-948b-56c977e4505c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>750412e5-88a0-45a3-b03c-fd33500c7518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Trường Tiểu học Thuần Hưng</value>
      <webElementGuid>a41e6b39-dce1-43db-817c-4b7b7b43b024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Trường Tiểu học Thuần Hưng</value>
      <webElementGuid>0a823d88-11d2-4349-8778-d0b018ce07ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-sd6j-container&quot;)</value>
      <webElementGuid>327dd773-0cb3-42da-933d-57d4f2a64659</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-sd6j-container']</value>
      <webElementGuid>8ae781bc-5f26-487e-b4b3-687832a05fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='setting-account']/div/div[3]/div/span/span/span/span</value>
      <webElementGuid>8622af18-0477-40ab-9239-eb3ddaed1acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn trường'])[1]/following::span[4]</value>
      <webElementGuid>dcede155-8628-4778-b0ea-c316b8600d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Huyện Khoái Châu'])[2]/following::span[6]</value>
      <webElementGuid>195e742e-7a30-4231-952b-5d8c22753b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nhận thông báo OLM:'])[1]/preceding::span[3]</value>
      <webElementGuid>054536e7-cba7-489d-8ff6-3f043c7ef1cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qua Zalo'])[1]/preceding::span[3]</value>
      <webElementGuid>34c0e226-ce2f-4af5-a860-e3c5a3143ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/span/span/span</value>
      <webElementGuid>9dd1d933-3eec-4780-8d57-8cca3381dbae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-sd6j-container' and @title = 'Trường Tiểu học Thuần Hưng' and (text() = 'Trường Tiểu học Thuần Hưng' or . = 'Trường Tiểu học Thuần Hưng')]</value>
      <webElementGuid>276e03dc-71a8-461b-84b5-e49c144cd29a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
