<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hng Yn</name>
   <tag></tag>
   <elementGuidId>66779fdb-8956-4e28-9698-e8452ec96b43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[5]/div/div[2]/div/div/div[1]/div[1]/div/span/span[1]/span/span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-82ht-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>124d0d8e-b221-4c61-8d71-afb18b0e8128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>bd51461c-ffb2-4d8c-866b-2d97edb4624b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-82ht-container</value>
      <webElementGuid>7a0be5e3-591f-4fe8-b032-865a579f3b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>a31d3dd2-581a-40cc-bced-b815d948ea10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f71874c9-32ae-44d7-966b-6705ff0d9a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Hưng Yên</value>
      <webElementGuid>55135f6c-2156-45fa-a407-e27d80d83841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hưng Yên</value>
      <webElementGuid>d5b12133-a7d6-4ae0-9c36-5e0bbdac2611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-82ht-container&quot;)</value>
      <webElementGuid>ed86d083-8fe9-4679-8715-985a3e2971e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-82ht-container']</value>
      <webElementGuid>72f2e04b-c8f0-4586-a564-5d50667bed76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='setting-account']/div/div/div/span/span/span/span</value>
      <webElementGuid>8b062f9b-ce39-4a7f-90c0-ec0dedadab7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn tỉnh/thành phố'])[1]/following::span[4]</value>
      <webElementGuid>2bd106e9-31d4-414a-86d6-c4bb4dbe697b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn quận/huyện'])[1]/preceding::span[3]</value>
      <webElementGuid>df774899-5bcc-4b9e-b303-802329912a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Huyện Khoái Châu'])[2]/preceding::span[3]</value>
      <webElementGuid>c2fdfb31-2159-4282-b9d5-011e792d9836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>0fe082db-eac3-4b9f-a9a1-02562299d0ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-82ht-container' and @title = 'Hưng Yên' and (text() = 'Hưng Yên' or . = 'Hưng Yên')]</value>
      <webElementGuid>e4e2195f-822d-428b-87f8-d0658238dd29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
