<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mt khu c_old-password</name>
   <tag></tag>
   <elementGuidId>25de8081-58af-4ec7-9aa9-0c537528dd12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;old-password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='old-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c40aed1-a328-417d-ba54-cf6a893540dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-password</value>
      <webElementGuid>b67c1e93-d990-4f72-b4e9-31df9dd5433b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>149ff730-0492-4859-a8c5-0dd92a1cb541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4c39039b-384d-4fb1-9725-5652fe070225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>old-password</value>
      <webElementGuid>9c9ea0b9-beb2-4e13-8842-e3295a9681bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập mật khẩu cũ của bạn</value>
      <webElementGuid>11081cab-fe19-4b71-a59d-5a312607a6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-reset-password&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered modal-dialog-scrollable&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[1]/div[@class=&quot;form-group position-relative&quot;]/input[@class=&quot;form-control input-password&quot;]</value>
      <webElementGuid>1228c256-ffd6-47e7-a07a-a670710ec947</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='old-password']</value>
      <webElementGuid>b20ace4a-fd03-4400-907b-ca6ed5aa70a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-reset-password']/div/div/div[2]/form/div/input</value>
      <webElementGuid>5c2bcb9c-4b1b-45ea-a2df-d2a40cea2c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/form/div/input</value>
      <webElementGuid>61a124a7-eb2c-4ce9-a5b5-b2bd8b5ca6e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'old-password' and @placeholder = 'Nhập mật khẩu cũ của bạn']</value>
      <webElementGuid>6b6246b4-9851-4f69-9898-9385206857ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
