<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PT</name>
   <tag></tag>
   <elementGuidId>b4c8b434-08d6-4d53-8425-f7d3c424abf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.olm-circle.olm-bg-primary.rounded-circle.border</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='dropdownMenuUser']/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>10ff11d4-b101-450e-a383-52ab9026579b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>olm-circle olm-bg-primary rounded-circle border </value>
      <webElementGuid>cb8bfad8-6a1c-49c3-ab28-ecb080288613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input</name>
      <type>Main</type>
      <value>phan thanh viet</value>
      <webElementGuid>2670fd3f-f1ad-4ee7-a0d0-7cb42c3ef41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PT</value>
      <webElementGuid>8ee37c76-822c-4185-a5c5-c5c245d86133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdownMenuUser&quot;)/div[@class=&quot;dropdown-box&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/span[@class=&quot;olm-circle olm-bg-primary rounded-circle border&quot;]</value>
      <webElementGuid>b437371d-1939-46d6-8014-a37cc55d76d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='dropdownMenuUser']/div/div/span</value>
      <webElementGuid>0fcadfd6-fbec-4ece-812c-ed6b82876403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đã tải hết thông báo'])[1]/following::span[1]</value>
      <webElementGuid>2d82d306-832a-4941-b7fa-e5e5ae8ed221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xem tất cả'])[1]/following::span[1]</value>
      <webElementGuid>330836d6-d4fc-4bdf-a597-fd1455b09cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phan Thanh Việt'])[1]/preceding::span[1]</value>
      <webElementGuid>1cde2f68-3b35-4bd8-9c10-1e4151b39fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phan Thanh Việt'])[2]/preceding::span[2]</value>
      <webElementGuid>896dd9e1-a339-446d-bafd-bdb979eb3e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PT']/parent::*</value>
      <webElementGuid>eb393ff3-46d6-4d33-9c39-ea43b298fcb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span</value>
      <webElementGuid>64dcd70b-87b7-4a9e-8fb6-e938cf32a930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'PT' or . = 'PT')]</value>
      <webElementGuid>845681dd-8510-40eb-8fe6-d470916959c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
